Repository QualityUnit/hugo-boilerplate, pull requests merged in 2025-09, with the labels that each got.

#151 [3670] compact pricing
  assets/css/main.css
  layouts/partials/components/lists/with_icon.html
  layouts/partials/sections/pricing/section.html
  layouts/shortcodes/pricing-section.html
Labels: needs-review

#162 [3645] Fixed video element padding and play button
  assets/css/components/youtube-video.css
  layouts/partials/sections/content/split_with_image.html
Labels: needs-review

#165 fix secondary buttons on the dark bg
  assets/css/main.css
Labels: bug

#168 [3832] mobile improvements
  layouts/blog/list.html
  layouts/partials/components/cards/post_card_with_image.html
  layouts/partials/head.html
  layouts/partials/related_content.html
  layouts/partials/sections/content/split_with_image.html
  layouts/partials/sections/content/split_with_image_cards.html
  layouts/partials/sections/hero/simple_centered.html
  layouts/partials/sections/hero/split_with_image.html
  layouts/partials/sections/hero/split_with_youtube_video.html
  layouts/partials/sections/pricing/with_comparison_table.html
Labels: needs-review

#170 removed 404 page
  layouts/_default/404.html
Labels: enhancement
